### PR TITLE
fix: send email with local name via custom client

### LINKED ISSUE #602: Email notifications: SMTP HELO check rejects "localhost"
Customer is trying to Integrate their SMTP server to Aqua but the test fails with the following Aqua GUI ERROR:

504 5.5.2 <localhost>: Helo command rejected: need fully-qualified hostname

**Failed to test notification output: 504 5.5.2 <localhost>: Helo command rejected: need fully-qualified hostname
[Postee] failed to send email: 504 5.5.2 <localhost>: Helo command rejected: need fully-qualified hostname**

SMTP Server Log:
**Jul 11 10:35:53 dz-smtp-01 postfix/submission/smtpd[12073]: NOQUEUE: reject: RCPT from [ec2-3-69-237-88.eu-central-1.compute.amazonaws.com](http://ec2-3-69-237-88.eu-central-1.compute.amazonaws.com/)[3.69.237.88]: 504 5.5.2 <localhost>: Helo command rejected: need fully-qualified hostname; from=[br_as@br.de](mailto:br_as@br.de)to=[christian.heigl@br.de](mailto:christian.heigl@br.de) proto=ESMTP helo=<localhost>**

Sending localhost is the default behaviour of the net/smtp package:
[smtp package - net/smtp - Go Packages](https://pkg.go.dev/net/smtp#Client.Hello). This needs to be changed.

### PR DESCRIPTION
**Pull request by afdesk**
There are cases when SMTP server needs fully-qualified client hostname.
so Postee should have a config for it.

it fixes #602

### CODE REVIEW

File: actions/email.go [hunk 1]
```diff
@@ -26,6 +27,7 @@ type EmailAction struct {
 	Port       int
 	Sender     string
 	Recipients []string
+	LocalName  string
```
Comment (roeelivaqua) [inline actions/email.go:30]: is LocalName the right name for this variable? Not DomainName maybe (as derived from fqdn)?

File: actions/email.go [hunk 2]
```diff
@@ -89,6 +95,58 @@ func (email *EmailAction) Send(content map[string]string) error {
 	return nil
 }
 
+func (email EmailAction) sendEmailWithCustomClient(addr string, a smtp.Auth, from string, to []string, msg []byte) error {
```
Comment (roeelivaqua) [inline actions/email.go:98]: maybe add some verbosity to this function? var names, logs, errors and docstrings(not necessary), to look feel and stay readable like the previous sendEmail implementation.

**Comment by roeelivaqua** [comment]
Thanks @afdesk ! Left some comments. Please note we may need a cherry-pick into postee-for-enterprise branch, hopefully this isn't a breaking change :)

File: actions/email.go (hunk 1 above)
Comment (afdesk) [reply actions/email.go:30]: I agree that `LocalName` isn't a right name. It should be changed.
also `DomainName` can be misleading for email settings, isn't it?

maybe something like `client-host-name` ?

File: actions/email.go (hunk 2 above)
Comment (afdesk) [reply actions/email.go:102]: yes, sure. I've added a comment. will think over it more.

**Comment by afdesk** [comment]
> Thanks @afdesk ! Left some comments. Please note we may need a cherry-pick into postee-for-enterprise branch, hopefully this isn't a breaking change :)

oh, thanks for the review. I missed it. 
yes, there are no breaking changes here.

**Comment by roeelivaqua** [comment]
hey @afdesk ! I was away for a few days - how are we doing on this PR? Ready for review?

**Review by roeelivaqua — APPROVED** [review]

**Comment by roeelivaqua** [comment]
LGTM @afdesk ! let's go ahead and merge, and we will open a cherry-pick into `postee-for-enterprise` branch.

**Review by roeelivaqua — APPROVED** [review]

**Review by simar7 — APPROVED** [review]
